# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 806)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBar = QtWidgets.QFrame(Dialog)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 38))
        self.titleBar.setStyleSheet(".QFrame {\n"
"    background-color: rgb(40, 57, 113);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.titleBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout_6.setContentsMargins(14, 2, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.titleLabel = QtWidgets.QLabel(self.titleBar)
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_6.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.titleBar)
        self.dialogFrame = QtWidgets.QFrame(Dialog)
        self.dialogFrame.setMinimumSize(QtCore.QSize(700, 700))
        self.dialogFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dialogFrame.setStyleSheet("QFrame#dialogFrame {\n"
"    background-color: rgb(138, 181, 203);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}\n"
"")
        self.dialogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dialogFrame.setObjectName("dialogFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dialogFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formFrame = QtWidgets.QFrame(self.dialogFrame)
        self.formFrame.setStyleSheet("QFrame#formFrame QLineEdit,QTimeEdit, QComboBox {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgb(171, 171, 171);\n"
"    max-height: 38px;\n"
"    min-height: 38px;\n"
"    font-family: Lato;\n"
"    font-size: 18px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QFrame#formFrame QLineEdit:hover,QTimeEdit:hover, QComboBox:hover {\n"
"    border: 2px solid rgb(41,128,241);\n"
"}\n"
"\n"
"\n"
"QFrame#formFrame QLineEdit:focus {\n"
"    border: 2px solid rgb(34, 110, 202);\n"
"    \n"
"    background-color: rgb(248, 249, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    image: url(:/icons/downArrow);\n"
"    max-height: 20px;\n"
"    min-height: 20px;\n"
"    max-width: 20px;\n"
"    min-width: 20px;\n"
"    top: 2px;\n"
"    right: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid gray;\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    combobox-popup: 0;\n"
"}\n"
"")
        self.formFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formFrame.setObjectName("formFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout.setContentsMargins(40, 30, 40, 5)
        self.gridLayout.setVerticalSpacing(22)
        self.gridLayout.setObjectName("gridLayout")
        self.dayGroupBox = QtWidgets.QGroupBox(self.formFrame)
        self.dayGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.dayGroupBox.setStyleSheet("QGroupBox QPushButton {\n"
"    background-color: rgb(255,255,255);\n"
"    border: none;\n"
"    border-right: 1px solid rgb(203, 203, 203);\n"
"    min-height: 42px;\n"
"    font-family: Lato;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox QPushButton:hover {\n"
"    background-color: rgb(216, 234, 255);\n"
"}\n"
"\n"
"QGroupBox QPushButton:checked {\n"
"    background-color: rgb(110, 180, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: none;\n"
"}")
        self.dayGroupBox.setTitle("")
        self.dayGroupBox.setObjectName("dayGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dayGroupBox)
        self.horizontalLayout_4.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sun_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.sun_btn.setStyleSheet("border-top-left-radius: 8px;\n"
"border-bottom-left-radius: 8px;")
        self.sun_btn.setObjectName("sun_btn")
        self.horizontalLayout_4.addWidget(self.sun_btn)
        self.mon_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.mon_btn.setStyleSheet("")
        self.mon_btn.setObjectName("mon_btn")
        self.horizontalLayout_4.addWidget(self.mon_btn)
        self.tue_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.tue_btn.setObjectName("tue_btn")
        self.horizontalLayout_4.addWidget(self.tue_btn)
        self.wed_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.wed_btn.setObjectName("wed_btn")
        self.horizontalLayout_4.addWidget(self.wed_btn)
        self.thu_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.thu_btn.setObjectName("thu_btn")
        self.horizontalLayout_4.addWidget(self.thu_btn)
        self.fri_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.fri_btn.setStyleSheet("")
        self.fri_btn.setObjectName("fri_btn")
        self.horizontalLayout_4.addWidget(self.fri_btn)
        self.sat_btn = QtWidgets.QPushButton(self.dayGroupBox)
        self.sat_btn.setStyleSheet("border-right: none;\n"
"border-top-right-radius: 8px;\n"
"border-bottom-right-radius: 8px;")
        self.sat_btn.setObjectName("sat_btn")
        self.horizontalLayout_4.addWidget(self.sat_btn)
        self.gridLayout.addWidget(self.dayGroupBox, 10, 1, 1, 2)
        self.linkLineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.linkLineEdit.setObjectName("linkLineEdit")
        self.gridLayout.addWidget(self.linkLineEdit, 14, 1, 1, 2)
        self.courseLineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.courseLineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.courseLineEdit.setStyleSheet("")
        self.courseLineEdit.setObjectName("courseLineEdit")
        self.gridLayout.addWidget(self.courseLineEdit, 2, 0, 1, 3)
        self.courseLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.courseLabel.setFont(font)
        self.courseLabel.setStyleSheet("")
        self.courseLabel.setObjectName("courseLabel")
        self.gridLayout.addWidget(self.courseLabel, 1, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.formFrame)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    font-family: Lato;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(171, 171, 171);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 1px solid rgb(41,128,241);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border: 2px solid rgb(41,128,241);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/checkbox);\n"
"    border: 1px solid rgb(138, 181, 203);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 17, 1, 1, 1)
        self.meetingLinkLabel = QtWidgets.QLabel(self.formFrame)
        self.meetingLinkLabel.setMinimumSize(QtCore.QSize(147, 0))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.meetingLinkLabel.setFont(font)
        self.meetingLinkLabel.setObjectName("meetingLinkLabel")
        self.gridLayout.addWidget(self.meetingLinkLabel, 14, 0, 1, 1)
        self.comboBoxFrame = QtWidgets.QFrame(self.formFrame)
        self.comboBoxFrame.setMinimumSize(QtCore.QSize(300, 40))
        self.comboBoxFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.comboBoxFrame.setStyleSheet("")
        self.comboBoxFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comboBoxFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.comboBoxFrame.setObjectName("comboBoxFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.comboBoxFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startTime = QtWidgets.QLabel(self.comboBoxFrame)
        self.startTime.setMinimumSize(QtCore.QSize(60, 0))
        self.startTime.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        self.startTime.setFont(font)
        self.startTime.setStyleSheet("")
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_3.addWidget(self.startTime)
        self.startComboBox = QtWidgets.QComboBox(self.comboBoxFrame)
        self.startComboBox.setMinimumSize(QtCore.QSize(150, 40))
        self.startComboBox.setStyleSheet("")
        self.startComboBox.setObjectName("startComboBox")
        self.horizontalLayout_3.addWidget(self.startComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.endTime = QtWidgets.QLabel(self.comboBoxFrame)
        self.endTime.setMinimumSize(QtCore.QSize(60, 0))
        self.endTime.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        self.endTime.setFont(font)
        self.endTime.setStyleSheet("")
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_3.addWidget(self.endTime)
        self.endComboBox = QtWidgets.QComboBox(self.comboBoxFrame)
        self.endComboBox.setMinimumSize(QtCore.QSize(150, 40))
        self.endComboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.endComboBox.setStyleSheet("")
        self.endComboBox.setObjectName("endComboBox")
        self.horizontalLayout_3.addWidget(self.endComboBox)
        self.gridLayout.addWidget(self.comboBoxFrame, 8, 1, 1, 2)
        self.idLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet("margin-top: 5px;")
        self.idLabel.setObjectName("idLabel")
        self.gridLayout.addWidget(self.idLabel, 15, 0, 1, 1)
        self.daysLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.daysLabel.setFont(font)
        self.daysLabel.setObjectName("daysLabel")
        self.gridLayout.addWidget(self.daysLabel, 10, 0, 1, 1)
        self.instructorEmailLineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.instructorEmailLineEdit.setStyleSheet("")
        self.instructorEmailLineEdit.setObjectName("instructorEmailLineEdit")
        self.gridLayout.addWidget(self.instructorEmailLineEdit, 5, 0, 1, 3)
        self.timeLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 8, 0, 1, 1)
        self.passLabel = QtWidgets.QLabel(self.formFrame)
        self.passLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.passLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.passLabel.setFont(font)
        self.passLabel.setObjectName("passLabel")
        self.gridLayout.addWidget(self.passLabel, 20, 0, 1, 1)
        self.instructorEmailLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.instructorEmailLabel.setFont(font)
        self.instructorEmailLabel.setObjectName("instructorEmailLabel")
        self.gridLayout.addWidget(self.instructorEmailLabel, 3, 0, 1, 2)
        self.joinLabel = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.joinLabel.setFont(font)
        self.joinLabel.setObjectName("joinLabel")
        self.gridLayout.addWidget(self.joinLabel, 12, 0, 1, 1)
        self.passcodeLineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.passcodeLineEdit.setObjectName("passcodeLineEdit")
        self.gridLayout.addWidget(self.passcodeLineEdit, 20, 1, 1, 2)
        self.meetingIDLineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.meetingIDLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.meetingIDLineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.meetingIDLineEdit.setStyleSheet("")
        self.meetingIDLineEdit.setObjectName("meetingIDLineEdit")
        self.gridLayout.addWidget(self.meetingIDLineEdit, 15, 1, 1, 2)
        self.radioBtnFrame = QtWidgets.QFrame(self.formFrame)
        self.radioBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radioBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radioBtnFrame.setObjectName("radioBtnFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.radioBtnFrame)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.linkRadioBtn = QtWidgets.QRadioButton(self.radioBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.linkRadioBtn.setFont(font)
        self.linkRadioBtn.setObjectName("linkRadioBtn")
        self.horizontalLayout_2.addWidget(self.linkRadioBtn)
        self.idRadioBtn = QtWidgets.QRadioButton(self.radioBtnFrame)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.idRadioBtn.setFont(font)
        self.idRadioBtn.setObjectName("idRadioBtn")
        self.horizontalLayout_2.addWidget(self.idRadioBtn)
        self.gridLayout.addWidget(self.radioBtnFrame, 12, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.formFrame)
        self.buttonFrame = QtWidgets.QFrame(self.dialogFrame)
        self.buttonFrame.setMinimumSize(QtCore.QSize(300, 60))
        self.buttonFrame.setStyleSheet("QPushButton {\n"
"    min-width: 120px;\n"
"    max-width: 120px;\n"
"    min-height: 30px;\n"
"    padding: 4px 0px;\n"
"    font: 16px Lato;\n"
"    background-color: white;\n"
"    border: none;\n"
"    margin: 0px 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame {\n"
"    margin-top: 30px;\n"
"}")
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 7, 0)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setStyleSheet("")
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout_5.addWidget(self.addBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_5.addWidget(self.cancelBtn)
        self.verticalLayout_2.addWidget(self.buttonFrame, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.dialogFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.courseLineEdit, self.instructorEmailLineEdit)
        Dialog.setTabOrder(self.instructorEmailLineEdit, self.startComboBox)
        Dialog.setTabOrder(self.startComboBox, self.endComboBox)
        Dialog.setTabOrder(self.endComboBox, self.sun_btn)
        Dialog.setTabOrder(self.sun_btn, self.mon_btn)
        Dialog.setTabOrder(self.mon_btn, self.tue_btn)
        Dialog.setTabOrder(self.tue_btn, self.wed_btn)
        Dialog.setTabOrder(self.wed_btn, self.thu_btn)
        Dialog.setTabOrder(self.thu_btn, self.fri_btn)
        Dialog.setTabOrder(self.fri_btn, self.sat_btn)
        Dialog.setTabOrder(self.sat_btn, self.linkRadioBtn)
        Dialog.setTabOrder(self.linkRadioBtn, self.idRadioBtn)
        Dialog.setTabOrder(self.idRadioBtn, self.linkLineEdit)
        Dialog.setTabOrder(self.linkLineEdit, self.meetingIDLineEdit)
        Dialog.setTabOrder(self.meetingIDLineEdit, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.passcodeLineEdit)
        Dialog.setTabOrder(self.passcodeLineEdit, self.addBtn)
        Dialog.setTabOrder(self.addBtn, self.cancelBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add New Class"))
        self.titleLabel.setText(_translate("Dialog", "Add new class"))
        self.sun_btn.setText(_translate("Dialog", "SUN"))
        self.mon_btn.setText(_translate("Dialog", "MON"))
        self.tue_btn.setText(_translate("Dialog", "TUE"))
        self.wed_btn.setText(_translate("Dialog", "WED"))
        self.thu_btn.setText(_translate("Dialog", "THU"))
        self.fri_btn.setText(_translate("Dialog", "FRI"))
        self.sat_btn.setText(_translate("Dialog", "SAT"))
        self.courseLabel.setText(_translate("Dialog", "Course Name"))
        self.checkBox.setText(_translate("Dialog", "Passcode required"))
        self.meetingLinkLabel.setText(_translate("Dialog", "Meeting Link"))
        self.startTime.setText(_translate("Dialog", "Start:"))
        self.endTime.setText(_translate("Dialog", "End:"))
        self.idLabel.setText(_translate("Dialog", "Meeting ID"))
        self.daysLabel.setText(_translate("Dialog", "Days"))
        self.timeLabel.setText(_translate("Dialog", "Time"))
        self.passLabel.setText(_translate("Dialog", "Meeting Passcode"))
        self.instructorEmailLabel.setText(_translate("Dialog", "Instructor Email (optional)"))
        self.joinLabel.setText(_translate("Dialog", "Join By"))
        self.linkRadioBtn.setText(_translate("Dialog", "Invitation Link"))
        self.idRadioBtn.setText(_translate("Dialog", "Meeting ID && Password"))
        self.addBtn.setText(_translate("Dialog", "Add"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
