# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 761)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))
        MainWindow.setStyleSheet("QScrollBar::vertical {\n"
"    border: none;\n"
"    background-color: rgb(85, 85, 127);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: none;\n"
"}\n"
"\n"
"QScrollBar::handle::vertical {\n"
"    background-color: rgb(115, 115, 171);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle::vertical::hover {\n"
"    background-color: rgb(129, 10, 209);\n"
"}\n"
"\n"
"QScrollBar::handle::vertical::pressed {\n"
"    background-color: rgb(102, 8, 170);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical {\n"
"    border: none;\n"
"    background-color: rgb(84, 84, 125);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical::hover {\n"
"    background-color: rgb(129, 10, 209);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical::pressed {\n"
"    background-color: rgb(102, 8, 170);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical {\n"
"    border: none;\n"
"    background-color: rgb(84, 84, 125);\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical::hover {\n"
"    background-color: rgb(129, 10, 209);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical::pressed {\n"
"    background-color: rgb(102, 8, 170);\n"
"}\n"
"\n"
"QScrollBar::up-arrow::vertical, QScrollBar::down-arrow::vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page::vertical, QScrollBar::sub-page::vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidgetLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralWidgetLayout.setContentsMargins(10, 10, 10, 10)
        self.centralWidgetLayout.setSpacing(0)
        self.centralWidgetLayout.setObjectName("centralWidgetLayout")
        self.shadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.shadowFrame.setFont(font)
        self.shadowFrame.setStyleSheet("#shadowFrame {\n"
"    border-radius: 10px;\n"
"}")
        self.shadowFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shadowFrame.setObjectName("shadowFrame")
        self.shadowFrameLayout = QtWidgets.QVBoxLayout(self.shadowFrame)
        self.shadowFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.shadowFrameLayout.setSpacing(0)
        self.shadowFrameLayout.setObjectName("shadowFrameLayout")
        self.title_bar = QtWidgets.QFrame(self.shadowFrame)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 44))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title_bar.setFont(font)
        self.title_bar.setStyleSheet(".QFrame {\n"
"background-color: rgb(40, 57, 113);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 0;\n"
"border-bottom-right-radius: 0;}")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.titleBarLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.titleBarLayout.setContentsMargins(0, 0, 0, 0)
        self.titleBarLayout.setSpacing(0)
        self.titleBarLayout.setObjectName("titleBarLayout")
        self.title_frame = QtWidgets.QFrame(self.title_bar)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background:none;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.hboxlayout.setContentsMargins(15, 0, 0, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.titleLabel = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel {\n"
"color: #ffffff;\n"
"}")
        self.titleLabel.setObjectName("titleLabel")
        self.hboxlayout.addWidget(self.titleLabel)
        self.titleBarLayout.addWidget(self.title_frame)
        self.btn_frame = QtWidgets.QFrame(self.title_bar)
        self.btn_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_frame.setFont(font)
        self.btn_frame.setStyleSheet("background: none;")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.btn_frame)
        self.btn_minimize.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_minimize.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setAcceptDrops(False)
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 9px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.btn_frame)
        self.btn_maximize.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_maximize.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_maximize.setFont(font)
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 9px;    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_2.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.btn_frame)
        self.btn_close.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_close.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 9px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.titleBarLayout.addWidget(self.btn_frame)
        self.shadowFrameLayout.addWidget(self.title_bar)
        self.backgroundFrame = QtWidgets.QFrame(self.shadowFrame)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.backgroundFrame.setFont(font)
        self.backgroundFrame.setStyleSheet(".QFrame {\n"
"    background-color: rgb(130,171,192);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.backgroundFrameLayout = QtWidgets.QVBoxLayout(self.backgroundFrame)
        self.backgroundFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.backgroundFrameLayout.setSpacing(0)
        self.backgroundFrameLayout.setObjectName("backgroundFrameLayout")
        self.content = QtWidgets.QFrame(self.backgroundFrame)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.content.setFont(font)
        self.content.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"\n"
"")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.contentLayout = QtWidgets.QVBoxLayout(self.content)
        self.contentLayout.setContentsMargins(-1, 40, -1, -1)
        self.contentLayout.setObjectName("contentLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.content)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollBar::vertical {\n"
"    border: none;\n"
"    background-color: rgb(85, 85, 127);\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1038, 525))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setStyleSheet("QWidget {\n"
"    background-color: rgb(130,171,192);\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollAreaLayout.setObjectName("scrollAreaLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.contentLayout.addWidget(self.scrollArea)
        self.backgroundFrameLayout.addWidget(self.content)
        self.newMeetingBtnFrame = QtWidgets.QFrame(self.backgroundFrame)
        self.newMeetingBtnFrame.setMinimumSize(QtCore.QSize(130, 60))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.newMeetingBtnFrame.setFont(font)
        self.newMeetingBtnFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.newMeetingBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newMeetingBtnFrame.setObjectName("newMeetingBtnFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.newMeetingBtnFrame)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.newMeetingBtn = QtWidgets.QPushButton(self.newMeetingBtnFrame)
        self.newMeetingBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.newMeetingBtn.setMaximumSize(QtCore.QSize(60, 58))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.newMeetingBtn.setFont(font)
        self.newMeetingBtn.setStyleSheet("QPushButton {\n"
"    color: rgba(129, 10, 209, 0.6);\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"    border-radius: 30px;\n"
"    border: 2px solid rgba(129, 10, 209, 0.6);\n"
"    text-align: center;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgba(129, 10, 209, 1);\n"
"    color: white;}")
        self.newMeetingBtn.setObjectName("newMeetingBtn")
        self.horizontalLayout_4.addWidget(self.newMeetingBtn)
        self.backgroundFrameLayout.addWidget(self.newMeetingBtnFrame, 0, QtCore.Qt.AlignRight)
        self.sizeGrip = QtWidgets.QFrame(self.backgroundFrame)
        self.sizeGrip.setMinimumSize(QtCore.QSize(20, 20))
        self.sizeGrip.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.sizeGrip.setFont(font)
        self.sizeGrip.setStyleSheet("")
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sizeGrip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sizeGrip.setObjectName("sizeGrip")
        self.backgroundFrameLayout.addWidget(self.sizeGrip, 0, QtCore.Qt.AlignRight)
        self.shadowFrameLayout.addWidget(self.backgroundFrame)
        self.backgroundFrame.raise_()
        self.title_bar.raise_()
        self.centralWidgetLayout.addWidget(self.shadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zoom Class Manager"))
        self.titleLabel.setText(_translate("MainWindow", "Zoom Class Manager"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.newMeetingBtn.setToolTip(_translate("MainWindow", "Add new meeting"))
        self.newMeetingBtn.setText(_translate("MainWindow", "+"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
